name: Sync Fork

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 12 * * *'
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: ip-scanner/cloudflare
          target_repository: ip-scanner-all/cloudflare
          upstream_branch: daily
          target_branch: daily
          force: true
          tags: true
